### ISSUE TITLE
explanation of how the app and it's underlying calculations work

### ISSUE THREAD

**Issue by DANIELKANTEK** [abuchmueller/amtGUI#1]
Hi Andreas,

I would like to know how the app performs statistical analysis of the iSSF. I'm using it for jaguar analysis.

Thanks

**Comment by abuchmueller** [comment]
Hello Daniel,

amtGUI is a graphical interface to the [`amt` R package](https://cran.r-project.org/web/packages/amt/index.html) aimed at researchers who want to conduct animal movement analysis but don't have strong background in R. As such, I was not involved in the mathematical framework or it's underlying calculations.
You can find more information of how it's underlying calculations in the `amt` reference manual linked above. 
The `amt` reference manual states that the iSSF function is a wrapper around `survival::clogit` i.e. is based on a conditional logit function.

For more information refer to the reference manual of the `amt` package linked above. I also recommend reading [this](https://arxiv.org/abs/1805.03227) paper by the original authors of the `amt` package.

**Comment by DANIELKANTEK** [comment]
thank you very much Andreas !!

Best,
